# Generated by Django 2.1.7 on 2019-02-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(null=True)),
                ('date', models.DateField()),
                ('finished', models.BooleanField()),
            ],
        ),
    ]
